### PR TITLE
Update examples react-scripts for Node.js 18

### PR DESCRIPTION
**Pull request by MikeMcC399**
This PR resolves issue https://github.com/cypress-io/github-action/issues/687 "react-scripts used in [example-wait-on](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-wait-on.yml) fail locally on Node.js 18 (LTS)"

In the following examples:

- [examples/v9/react-scripts](https://github.com/cypress-io/github-action/tree/master/examples/v9/react-scripts)
- [examples/react-scripts](https://github.com/cypress-io/github-action/tree/master/examples/react-scripts)

the following versions are bumped:

- [react](https://www.npmjs.com/package/react) to 18.2.0 (latest)
- [react-dom](https://www.npmjs.com/package/react-dom) to 18.2.0 (latest)
- [react-scripts](https://www.npmjs.com/package/react-scripts) from 3.4.4 to 5.0.1 (latest)

### GitHub test

Check the Actions log on https://github.com/cypress-io/github-action/actions/workflows/example-wait-on.yml?query=branch%3Amaster and ensure that the Status is "Success".

- [examples/v9/react-scripts](https://github.com/cypress-io/github-action/tree/master/examples/v9/react-scripts) is used in jobs:
    - wait-on-react-scripts-v9
    - wait-using-custom-command-v9
- [examples/react-scripts](https://github.com/cypress-io/github-action/tree/master/examples/react-scripts) is used in jobs:
    - wait-on-react-scripts
    - wait-using-custom-command

### Local test

Open a terminal window on a local clone of the repository:

```bash
cd examples/v9/react-scripts
nvm use 18.13.0
npm ci
npm start
```
Ensure the message:
"webpack compiled successfully"
appears and that there are no error messages displayed. (See below for comment on deprecation warnings.)

Following on from the previous test, to now check in `examples/react-scripts` ...

```bash
cd ../../react-scripts
nvm use 18.13.0
npm ci
npm start
```

Ensure the message:
"webpack compiled successfully"
appears and that there are no error messages displayed.

*Note that when running `npm start`, deprecation warnings appear. This is a known issue 11860 in https://github.com/facebook/create-react-app/issues. The warnings are:*

```text
DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE
DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE
```

### CODE REVIEW

**Comment by MikeMcC399** [comment]
Verified in run [3967183798](https://github.com/cypress-io/github-action/actions/runs/3967183798) with individual jobs:

- [wait-on-react-scripts-v9](https://github.com/cypress-io/github-action/actions/runs/3967183798/jobs/6798859789)
- [wait-using-custom-command-v9](https://github.com/cypress-io/github-action/actions/runs/3967183798/jobs/6798860630)
- [wait-on-react-scripts](https://github.com/cypress-io/github-action/actions/runs/3967183798/jobs/6798859638)
- [wait-using-custom-command](https://github.com/cypress-io/github-action/actions/runs/3967183798/jobs/6798860450)

**Review by Trealent777 — APPROVED** [review]

**Review by Trealent777 — APPROVED** [review]

**Comment by MikeMcC399** [comment]
- In draft pending https://github.com/cypress-io/github-action/pull/747

**Comment by MikeMcC399** [comment]
@jaffrepaul 

This PR is now rebased and ready for review and merge.

**Review by jaffrepaul — APPROVED** [review]
👍

**Pull request merged**
