### PR TITLE
ci: rework example-basic

### PR DESCRIPTION
**Pull request by MikeMcC399**
## Change

The workflow [.github/workflows/example-basic.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-basic.yml) is refactored as follows:

- The workflow is converted to use a matrix of operating systems for clarity
- `ubuntu-24.04` is added
- `latest` operating systems are pinned to concrete versions for stability:
  - `windows-latest` changed to [windows-2022](https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md) (Windows Server 2022)
  - `macos-latest` changed to [macos-14](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md) (macOS 14 Arm64)

### CODE REVIEW

**Comment by MikeMcC399** [comment]
This is in preparation for adding `ubuntu-24.04` which is expected to exit beta status soon.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

PR from last week requesting review and merge!
I'd like to be ready for `ubuntu-24.04`.

**Review by jennifer-shehane — APPROVED** [review]
Sorry I missed this one!

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

> Sorry I missed this one!

Thank you for merging! Now this repo is using `ubuntu-24.04` as default (this is now also labeled `ubuntu-latest`).

At some stage I would expect `ubuntu-20.04` to be deprecated and withdrawn, as GitHub's policy is to support only 2 versions of each OS (see [GA](https://github.com/actions/runner-images/blob/main/README.md#ga)). That would be the trigger to remove the use of Ubuntu `20.04` in this GitHub Actions repo.

**Pull request merged**
