### PR TITLE
feat:Allow customization of the cache key for binary and NPM cache.

### PR DESCRIPTION
**Pull request by smil2k**
Currently the lock file hash calculated regardless whether the key specified or not.

### CODE REVIEW

**Comment by MikeMcC399** [comment]
Hi @smil2k 

I'm not sure that `cache` is the right way to handle lockfiles in a different place.

Normally we would expect `package.json` to be together with its lock file, which could be `package-lock.json` (npm), `pnpm-lock.yml` (pnpm) or `yarn.lock` (Yarn). 

Do you have a special use-case that you would like to explain? Which package manager are you using? It's possible that `github-action` is not the right solution for you if you need to by-pass its standard functionality.

The [project](https://github.com/cypress-io/github-action#project) parameter or the [working-directory](https://github.com/cypress-io/github-action#working-directory) parameter would the regular way to make sure that `github-action` finds the right lock file and installs the dependencies using one of the supported package managers (npm, pnpm or Yarn).

**Comment by MikeMcC399** [comment]
Also you need to review the [CONTRIBUTING](https://github.com/cypress-io/github-action/blob/master/CONTRIBUTING.md) advice for submissions, since this PR is incomplete without the changes in the `dist` directory. You would need this in order to test your contribution.

**Comment by MikeMcC399** [comment]
I notice that you have introduced a new parameter `binary-cache-key`, however you did not add this to [action.yml](https://github.com/cypress-io/github-action/blob/master/action.yml) so that cannot work.

Have you tried to test your submission?

**Comment by smil2k** [comment]
> Hi @smil2k
> 
> I'm not sure that `cache` is the right way to handle lockfiles in a different place.
> 
> Normally we would expect `package.json` to be together with its lock file, which could be `package-lock.json` (npm), `pnpm-lock.yml` (pnpm) or `yarn.lock` (Yarn).
> 
> Do you have a special use-case that you would like to explain? I see from the title that you are targetting npm. It's possible that `github-action` is not the right solution for you if you need to by-pass its standard functionality.
> 
> The [project](https://github.com/cypress-io/github-action#project) parameter or the [working-directory](https://github.com/cypress-io/github-action#working-directory) parameter would be the regular way to make sure that `github-action` finds the right lock file and installs the dependencies using one of the supported package managers (npm, pnpm or Yarn).

Thank you for the quick reply. 

We are using a mono repo and workspace package.json. The cypress parts are in an isolated directory within the repo. In this case NPM does not produce a lock file within the workspace, but one level higher in the hierarchy. 

I could workaround it with a link at the moment. I was thinking on the ability to specify the lock location, but as far as I saw you only needed it for the hash calculation. This is why I opted for allowing cache keys to be specified by hand, which makes the location of the package-lock irrelevant.

**Comment by smil2k** [comment]
> I notice that you have introduced a new parameter `binary-cache-key`, however you did not add this to [action.yml](https://github.com/cypress-io/github-action/blob/master/action.yml) so that cannot work.
> 
> Have you tried to test your submission?

Sorry, I though first that it would be only shifting one line down, then found the location of the other cache...
I will go though the checklist soon.

**Comment by MikeMcC399** [comment]
It sounds like you have a [project](https://github.com/cypress-io/github-action#project) configuration.

Would you like to compare this with the example 

https://docs.cypress.io/guides/guides/command-line#cypress-run-project-lt-project-path-gt >

https://github.com/cypress-io/cypress-test-nested-projects ?

**Comment by MikeMcC399** [comment]
Another way to handle this is like the example in https://github.com/bahmutov/cypress-gh-action-monorepo/blob/master/.github/workflows/test.yml

First call the action to install dependencies, then call the action using the working-directory parameter without install.

**Comment by smil2k** [comment]
I think I did what I could to follow the contributions file. 

Anyhow, your solution with separate install and run would probably also fit the bill. So if you think that this change makes this action more complex, then go ahead an close the pull.

**Comment by MikeMcC399** [comment]
@smil2k 

It's good if you think that your use case can be covered by following the example. I've copied it here and modified it a little (I changed the `checkout` call to a specific version and I removed the reference to `yarn`):

```
name: E2E
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: cypress-io/github-action@v5
        with:
          # just perform install
          runTests: false
      - name: Run e2e tests
        uses: cypress-io/github-action@v5
        with:
          # we have already installed all dependencies above
          install: false
          # Cypress tests and config file are in "e2e" folder
          working-directory: e2e
```

I'm actually just a community Contributor, not a moderator, so I have to leave it to you or to the Cypress.io team to close the PR. I think that would be the best decision here, as the change doesn't seem to be necessary.

**Comment by nagash77** [comment]
> I think I did what I could to follow the contributions file.
> 
> Anyhow, your solution with separate install and run would probably also fit the bill. So if you think that this change makes this action more complex, then go ahead an close the pull.

I am going to close this PR

**Pull request closed without merging**
