### PR TITLE
fix: windows build with ping.js

### PR DESCRIPTION
**Pull request by MikeMcC399**
This PR fixes an issue building and committing the action on Microsoft Windows.

## Issue

On Windows, compiling the source code using [vercel/ncc](https://github.com/vercel/ncc) would cause Windows-style `CRLF` end-of-line characters to be embedded in [dist/index.js](https://github.com/cypress-io/github-action/blob/master/dist/index.js), but only for the portion of code coming from [src/ping.js](https://github.com/cypress-io/github-action/blob/master/src/ping.js). Other parts of the file [dist/index.js](https://github.com/cypress-io/github-action/blob/master/dist/index.js) were using unix-style `LF` as end-of-line character.

Carrying out the same action on a unix system such as Ubuntu results in only `LF` characters being used.

This would lead to unnecessary `git` differences if the action were changed and committed to GitHub from unix and Windows in turn.

## Resolution

The `run format` command is changed from:

`"format": "prettier --write index.js"` to
`"format": "prettier --write index.js src/ping.js"`

[prettier](https://github.com/prettier/prettier) is now used additionally on [src/ping.js](https://github.com/cypress-io/github-action/blob/master/src/ping.js) to pre-process this source file and convert the end-of-line character consistently to `LF` before it is fed to `ncc build` for compilation.

The [Prettier: End of Line](https://prettier.io/docs/en/options.html#end-of-line) option is set to `lf` by default in `v2.0.0` and is not overridden in [.prettierrc.json](https://github.com/cypress-io/github-action/blob/master/.prettierrc.json). The action currently uses v2.8.4 of Prettier, so this default applies already.

This PR is a prerequisite for re-enabling a [husky](https://typicode.github.io/husky/) pre-commit hook (see also https://github.com/cypress-io/github-action/issues/743) so that it can work consistently across operating systems (unix / Windows).

### Ubuntu

On Ubuntu 22.04, execute:

```bash
npm ci
npm run format
npm run build
git status
```

confirm the message:

"nothing to commit, working tree clean"

### Microsoft Windows

Move to Microsoft Windows (11 Pro) and execute

```bash
git config --global core.autocrlf
```

Confirm that the default value of `true` is set (see [Git Configuration](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration)). If not, then execute

```bash
git config --global core.autocrlf true
```

Now execute:

```bash
npm ci
npm run format
npm run build
git add .
git status
```

confirm the message:

"nothing to commit, working tree clean"

### CODE REVIEW

**Comment by jaffrepaul** [comment]
There are two issues/PRs regarding ping.js updates. Can either of these be folded into this work to creating a larger update?

- https://github.com/cypress-io/github-action/pull/600
- https://github.com/cypress-io/github-action/issues/333

**Comment by MikeMcC399** [comment]
@jaffrepaul 

> There are two issues/PRs regarding ping.js updates. Can either of these be folded into this work to creating a larger update?
> 
> * [feat: make conditions of ping more explicit #600](https://github.com/cypress-io/github-action/pull/600)
> * [Ping every second or every N seconds #333](https://github.com/cypress-io/github-action/issues/333)

This PR is not modifying the function of [src/ping.js](https://github.com/cypress-io/github-action/blob/master/src/ping.js) at all, so it does not make sense to combine the above two PRs into this PR. Those PRs should be handled separately from this one.

All that this PR does is to make sure that `CRLF` ìs stripped off before [src/ping.js](https://github.com/cypress-io/github-action/blob/master/src/ping.js) is handed to `ncc build` for compilation.

**Review by AtofStryker — APPROVED** [review]

**Comment by MikeMcC399** [comment]
@AtofStryker 
Will you arrange for a second reviewer for this PR? It is one of the prerequisites for supporting Renovate to become more automated when dependencies are involved that flow into the action build.

**Comment by AtofStryker** [comment]
@MikeMcC399 I can take care of that. @lmiller1990 can you take a look here as well?

**Review by lmiller1990 — APPROVED** [review]

**Comment by lmiller1990** [comment]
🚀

**Pull request merged**
