### PR TITLE
Update wait-on-vite example to current versions

### PR DESCRIPTION
**Pull request by MikeMcC399**
This PR implements the suggestion from issue https://github.com/cypress-io/github-action/pull/756 "examples/wait-on-vite uses vite 2 beta" to update the Vite version to a non-beta version.

For the legacy (v9) and current config example versions, the wait-on-vite app is replaced by the standard example created by `npm create vite` with options Vanilla and JavaScript.

- [examples/wait-on-vite](https://github.com/cypress-io/github-action/tree/master/examples/wait-on-vite) is updated using `npm create vite@4`.

- [examples/v9/wait-on-vite](https://github.com/cypress-io/github-action/tree/master/examples/v9/wait-on-vite) is updated using `npm create vite@3`.

In [.github/workflows/example-wait-on.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-wait-on.yml) changes are made to align with default Vite values / settings:

| Item         | Old       | New         |
| ------------ | --------- | ----------- |
| port         | 3000      | 5173        |
| start server | npm start | npm run dev |

### Local test

Execute:

```bash
cd examples/wait-on-vite
npm ci
npm run dev
```
Check that server announces itself with VITE v4.0.4.

In a separate terminal window execute:
```bash
cd examples/wait-on-vite
npm test
```
ensuring that the Cypress test runs successfully.

In the server terminal window, press q to quit the server.

```bash
cd ../v9/wait-on-vite
npm ci
npm run dev
```
Check that server announces itself with VITE v3.2.5.

Switch to the separate test terminal window and execute:
```bash
cd ../v9/wait-on-vite
npm test
```
and ensure that the Cypress test for the v9 version runs successfully.

### GitHub Action test

Run [.github/workflows/example-wait-on.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-wait-on.yml) and check that jobs

- `wait-on-vite-v9` and
- `wait-on-vite`

show success.

### CODE REVIEW

**Comment by MikeMcC399** [comment]
- Leaving in Draft status until PR https://github.com/cypress-io/github-action/pull/747 is merged.

**Comment by jaffrepaul** [comment]
This looks goo @MikeMcC399. Have you uncovered any intel on the errors indicated here? https://github.com/cypress-io/github-action/actions/runs/4143979840/jobs/7166507634#step:3:47

**Comment by MikeMcC399** [comment]
@jaffrepaul 

> Have you uncovered any intel on the errors indicated here?

This is a general Cypress issue related to running under GitHub runners or Docker containers.

## Cypress 12.x

Under Cypress 12.4.1 with `ubuntu-20.04` 

```text
[1867:0210/202930.349866:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
```
and `ubuntu-22.04` GitHub runners an error message always appears:

```text
[1861:0210/202926.180966:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
```

- This is the subject of issue https://github.com/cypress-io/cypress/issues/25357 with the Cypress E2E team.

## Cypress 9.7.0

Under Cypress 9.7.0 with ubuntu-20.04 and ubuntu-22.04 an additional message "ERROR:sandbox_linux.cc(377)" is output:

```text
[2228:0210/124337.097768:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[2228:0210/124337.106162:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
```

Neither errors prevent Cypress tests from succeeding.

- The error message "ERROR:sandbox_linux.cc(377)" was reported in https://github.com/cypress-io/cypress/issues/14558 and is unresolved.

- There may be a solution to https://github.com/cypress-io/cypress/issues/25357 for Cypress 12.x, however based on previous discussions I would not expect this to be backported to Cypress 9.x. @lmiller1990 may be able to provide more background information.

**Comment by lmiller1990** [comment]
We generally won't backport any fixes to olde versions of Cypress - since that one you are referring to is purely cosmetic, non a blocker to running tests, I think it's fine to move forward as is.

**Comment by jaffrepaul** [comment]
Thanks for clarifying @MikeMcC399!

**Review by jaffrepaul — APPROVED** [review]

**Comment by jaffrepaul** [comment]
Yes. I've seen this happen before, but haven't had the bandwidth to get to the root cause. Will get a look at renovate config as a possible solution.

**Pull request merged**
