### PR TITLE
fix(deps): update @actions/cache to 4.0.0

### PR DESCRIPTION
**Pull request by MikeMcC399**
- supersedes PR https://github.com/cypress-io/github-action/pull/1327

## Issue

- GitHub has released a new version of the npm module [@actions/cache](https://www.npmjs.com/package/@actions/cache) with the deprecation notice:

> The new service will gradually roll out as of February 1st, 2025. The legacy service will also be sunset on the same date. Changes in this release are fully backward compatible.

> All previous versions of this package will be deprecated. We recommend upgrading to version 4.0.0 as soon as possible before February 1st, 2025.

The new version is [@actions/cache@4.0.0](https://github.com/actions/toolkit/releases/tag/%40actions%2Fcache%404.0.0)

See also [@actions/cache Package Deprecation Notice. Upgrade to the latest 4.0.0 or higher before February 1st 2025](https://github.com/actions/toolkit/discussions/1890).

- Renovate attempted to update in PR https://github.com/cypress-io/github-action/pull/1327 however this fails in CI because the action needs to be re-built - see https://github.com/cypress-io/github-action/issues/1252.

## Change

- Update to [@actions/cache@4.0.0](https://github.com/actions/toolkit/releases/tag/%40actions%2Fcache%404.0.0) and re-build the action.

### CODE REVIEW

**Comment by MikeMcC399** [comment]
It's not clear why this is failing. I don't have access to the details:

```text
security/snyk (Cypress Tools) — 1 test has failed
```

**Review by jennifer-shehane — APPROVED** [review]

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

Thanks for passing on the vulnerability assessment from SNYK. I will check.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

- I reported the issue in https://github.com/actions/toolkit/issues/1901 and it is due to a transient dependency `dot-object` not being updated.  `glob` was already re-written to eliminate `inflight`.

We can leave this issue in draft until either the cut-off date Feb 2025 is reached or the vulnerability is resolved, which ever happens first.

If this PR is merged without resolution, then every subsequent PR is going to get flagged by SNYK, which would be annoying.

BTW: The Cypress binary is also distributing `inflight` through `glob`.

**Comment by MikeMcC399** [comment]
- [@actions/cache@4.0.0](https://github.com/actions/toolkit/releases/tag/%40actions%2Fcache%404.0.0) has significant supportability issues at this time, as raised in https://github.com/actions/toolkit/issues/1901#issuecomment-2541163611 . I prefer to close this PR now and wait for a response from the GitHub Toolkit team before deciding on next steps.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

GitHub maintainers have acknowledged the issue (see https://github.com/actions/toolkit/discussions/1890#discussioncomment-11581036) and have added it to their backlog to resolve in the next minor release of `@actions/cache@4`.

**Comment by MikeMcC399** [comment]
https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes

image

According to the notice from GitHub, if this PR is not merged, then the action will fail from Feb 1, 2025 onwards.

**Pull request closed without merging**
