### PR TITLE
fix: update failed tests

### PR DESCRIPTION
**Pull request by jaffrepaul**
Targeting a few failing tests that have been part of the previous GHA releases with some fixes.

There are related open issues [#1](https://github.com/cypress-io/cypress/issues/22086), [#2](https://github.com/cypress-io/cypress/issues/18919), [#3](https://github.com/cypress-io/github-action/issues/104) with FF that still cause flake in one test that will need a separate effort.

### CODE REVIEW

**Comment by MikeMcC399** [comment]
@jaffrepaul 

I see you are making good progress on eliminating some of the issues here! Whilst I was trying to find out what was going on with the Node.js issue I noticed that the deprecated `ubuntu-18.04` is still in use. It would probably overload this PR if you put additional changes in here, so instead I opened a new issue https://github.com/cypress-io/github-action/issues/648. Perhaps you already had something planned here anyway?

**Review by jordanpowell88 — APPROVED** [review]

**Comment by MikeMcC399** [comment]
@jaffrepaul 

This was 99% successful (110 of 111 checks passed) 👍🏻 
Was the remaining failure just the flaky Firefox test you referred to?

BTW: Would you consider making your (presumed) membership of the https://github.com/cypress-io organization visible? See GitHub help [Publicizing or hiding organization membership](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/publicizing-or-hiding-organization-membership).

**Comment by jaffrepaul** [comment]
@MikeMcC399 Yes, see the original PR message above. Good call on the org visibility ✅ I merged this without making a release yet because I'd like to add some of the additional dependency updates as well first.

**Comment by MikeMcC399** [comment]
@jaffrepaul 

> Good call on the org visibility ✅ 

Thank you for enabling this!

> I merged this without making a release yet because I'd like to add some of the additional dependency updates as well first.

That makes sense. Different workflows need to be updated and the README documentation as well, which will probably take several steps. Once everything is updated and consistent it would be worthwhile declaring a release. Anybody who is subscribed to releases would then get notified. Most users won't need to know about individual updates.

**Pull request merged**
