### PR TITLE
feat(deps): update cypress to 13.0.0

### PR DESCRIPTION
**Pull request by MikeMcC399**
This PR updates the [examples](https://github.com/cypress-io/github-action/tree/master/examples) to [Cypress 13.0.0](https://docs.cypress.io/guides/references/changelog#13-0-0) released August 29, 2023.

Since Cypress `13.0.0` is a major version release, this PR is declared as a feature update for increased visibility and to ensure that the README on https://www.npmjs.com/package/@cypress/github-action is updated.

### CODE REVIEW

**Review by nagash77 — APPROVED** [review]

**Comment by nagash77** [comment]
Thanks for doing this so quickly @MikeMcC399 !  You rock!

**Comment by MikeMcC399** [comment]
@nagash77 

Congratulations to the team for the v13 release! 🚀 

It's great to see all the preparations worked for `github-action` and the merge went smoothly.

**Comment by MikeMcC399** [comment]
@nagash77 

I guess I spoke too soon 🙁 !

There seems to be a problem with the npm registry https://www.npmjs.com/package/@cypress/github-action 

image

It also affects https://www.npmjs.com/package/cypress and other packages which were published today.

For this repo I will report the issue to npm support.

**Comment by MikeMcC399** [comment]
npm has sorted itself out apparently. No further action needed.
https://www.npmjs.com/package/@cypress/github-action now shows the README contents.

**Comment by nagash77** [comment]
Thanks for following up on that @MikeMcC399 !

**Comment by MikeMcC399** [comment]
@nagash77 

> Thanks for following up on that!

You're welcome! It had me worried to begin with until I realised it was a general problem affecting lots of other packages.

**Pull request merged**
