### PR TITLE
Upgrade version in examples

### PR DESCRIPTION
**Pull request by karlhorky**
Hi there 👋 As always, thanks for your continued efforts in the end to end / integration test automation space!

Here's a quick PR to upgrade to [the new `5.0.0` version](https://github.com/cypress-io/github-action/releases/tag/v5.0.0)

### CODE REVIEW

**Review by jaffrepaul — APPROVED** [review]
thx!

**Comment by MikeMcC399** [comment]
Comments in various workflows in https://github.com/cypress-io/github-action/tree/master/.github/workflows refer to

`cypress-io/github-action@v2` instead of `v5` e.g.

https://github.com/cypress-io/github-action/blob/78da0ecebc74b45a47b9f48bd2ecc8011471288a/.github/workflows/example-basic.yml#L16-L18

Also https://github.com/cypress-io/github-action/blob/78da0ecebc74b45a47b9f48bd2ecc8011471288a/.github/workflows/example-component-test.yml#L10

uses `@v4` instead of `@v5`

These should also be updated, either in this PR or in a separate one.

**Comment by jaffrepaul** [comment]
@karlhorky can you comb through and update the comments as well as @MikeMcC399 mentioned?

**Comment by karlhorky** [comment]
@MikeMcC399 thanks, merged!

**Comment by karlhorky** [comment]
Thanks for the merge!

**Comment by MikeMcC399** [comment]
@karlhorky 
Thanks also to you for taking the initiative and for merging in my additions. Thanks also of course to @jaffrepaul!

**Pull request merged**
