### PR TITLE
test: Replace react-scripts example by nextjs example

### PR DESCRIPTION
**Pull request by MikeMcC399**
This PR resolves https://github.com/cypress-io/github-action/issues/866 "Deprecations related to examples/react-scripts".

It implements the suggestion to replace [examples/react-scripts](https://github.com/cypress-io/github-action/tree/master/examples/react-scripts) by a new example based on [Start a New React Project](https://react.dev/learn/start-a-new-react-project) using [Next.js](https://nextjs.org/).

The setup follows [Create a Next.js App](https://nextjs.org/learn/basics/create-nextjs-app).

## Changes

1. [examples/react-scripts](https://github.com/cypress-io/github-action/tree/master/examples/react-scripts) is removed.
2. In its place `examples/nextjs` is added.
3. The workflow [.github/workflows/example-wait-on.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-wait-on.yml) is modified to use `examples/nextjs` instead of [examples/react-scripts](https://github.com/cypress-io/github-action/tree/master/examples/react-scripts).
4. The [scripts/update-cypress-latest-npm.sh](https://github.com/cypress-io/github-action/blob/master/scripts/update-cypress-latest-npm.sh) is modified to update `examples/nextjs` to `cypress@latest` instead of [examples/react-scripts](https://github.com/cypress-io/github-action/tree/master/examples/react-scripts).

### Local

Execute:

```bash
npm ci
npm outdated
npm audit
npm run update:cypress
```

and ensure

1. no errors are reported
2. no out-of-date dependencies are reported
3. 0 vulnerabilities are reported

### GitHub

Examine workflow log from https://github.com/cypress-io/github-action/actions/workflows/example-wait-on.yml and ensure that the jobs:

- `wait-on-nextjs`
- `wait-using-custom-command`

complete successfully.

`wait-on` is using `localhost` showing that the workaround of `127.0.0.1` needed for the `react-scripts` example is not necessary for `nextjs`

### CODE REVIEW

**Comment by MikeMcC399** [comment]
Job [8402951508](https://github.com/cypress-io/github-action/actions/runs/4734266636/jobs/8402951508) failed due to flaky network access. This is not an error in this PR.

```
https://example.cypress.io/

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: ESOCKETTIMEDOUT

```

**Review by jordanpowell88 — APPROVED** [review]
LGTM. Great job @MikeMcC399

**Review by jaffrepaul — APPROVED** [review]
Good stuff. Thanks Mike!

**Comment by MikeMcC399** [comment]
@jordanpowell88 / @jaffrepaul 

Thanks guys! The difficult part is mostly figuring out what the right solution should be. Implementing it is often relatively straightforward.

**Pull request merged**
