### PR TITLE
Update examples to cypress 12.7.0

### PR DESCRIPTION
**Pull request by MikeMcC399**
This PR updates the Cypress 12.x [examples](https://github.com/cypress-io/github-action/tree/master/examples) to [Cypress 12.7.0](https://docs.cypress.io/guides/references/changelog#12-7-0) released Feb 24, 2023.

Versions are now exact for all examples.
Previously `basic-pnpm` was using semantic versioning `^12.6.0`. It now uses `12.7.0` like the other examples.

### CODE REVIEW

**Comment by MikeMcC399** [comment]
- 4 failing checks are subject of issue https://github.com/cypress-io/github-action/issues/802 and proposed for solution in PR https://github.com/cypress-io/github-action/pull/803

**Review by AtofStryker — APPROVED** [review]

**Comment by MikeMcC399** [comment]
Hi @AtofStryker 

Thank you for approving this PR!

Just as an aside, would you mind checking out GitHub Help [Publicizing or hiding organization membership](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/publicizing-or-hiding-organization-membership) to get your membership of cypress.io public so you appear here with a "Member" badge? I didn't initially realize that you are part of the Cypress organization.

**Review by mjhenkes — APPROVED** [review]

**Comment by mjhenkes** [comment]
Thanks @MikeMcC399!

**Comment by MikeMcC399** [comment]
@mjhenkes 
> Thanks

You are very welcome!

- I posted PR https://github.com/cypress-io/github-action/pull/779 with a script to automate updating to cypress@latest. This isn't assigned to anybody at this time, so I'm still waiting for a review.

**Comment by mjhenkes** [comment]
I'm on it!

**Pull request merged**
