### PR TITLE
Record to Cypress Cloud in fork

### PR DESCRIPTION
**Pull request by MikeMcC399**
This PR resolves the issue https://github.com/cypress-io/github-action/issues/693 "Workflows using Cypress Cloud fail in fork".

It follows the recommendation in the [README: Record test results on Cypress Cloud](https://github.com/cypress-io/github-action/blob/master/README.md#record-test-results-on-cypress-cloud) documentation, Tip 4, to pass the project id using an environment variable.

The two examples are modified so that they accept and use a new GitHub Actions variable `EXAMPLE_PROJECT_ID` in addition to the existing `EXAMPLE_RECORDING_KEY` which is an Actions secret:

- [example-custom-ci-build-id](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-custom-ci-build-id.yml)
- [example-recording](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-recording.yml)

This is backward compatible to the current workflows.

In the parent repository [cypress-io/github-action](https://github.com/cypress-io/github-action) the Actions secret `EXAMPLE_RECORDING_KEY` is defined for the Project ID `3tb7jn`. Runs are publicly viewable via the Cypress Cloud on https://cloud.cypress.io/projects/3tb7jn.

If fork users define `EXAMPLE_PROJECT_ID` as Actions variable and `EXAMPLE_RECORDING_KEY` as Actions secret in their forked repository then the workflows record into the user's own project. If this step is not taken, then the workflows will simply continue to report failures if they are triggered in a fork, exactly as happens before this PR was introduced.

README files have been added as:

- examples/v9/recording/README.md
- examples/recording/README.md

to explain how to obtain and add a user's own `EXAMPLE_PROJECT_ID` and `EXAMPLE_RECORDING_KEY`.

The README files are reviewable in

- https://github.com/MikeMcC399/github-action/blob/feat/record-in-fork/examples/v9/recording/README.md
- https://github.com/MikeMcC399/github-action/blob/feat/record-in-fork/examples/recording/README.md

### Backwards compatibility

Ensure that the workflows for the parent repository [cypress-io/github-action](https://github.com/cypress-io/github-action) continue to report success:

- https://github.com/cypress-io/github-action/actions/workflows/example-custom-ci-build-id.yml?query=branch%3Amaster
- https://github.com/cypress-io/github-action/actions/workflows/example-recording.yml?query=branch%3Amaster

### New functionality

Follow the instructions to create new `EXAMPLE_PROJECT_ID` Actions variable and `EXAMPLE_RECORDING_KEY` Actions secret and check that the results are published on Cypress Cloud.

### CODE REVIEW

**Comment by MikeMcC399** [comment]
- Set to draft waiting for PR https://github.com/cypress-io/github-action/pull/690

**Comment by MikeMcC399** [comment]
Reworked to set `EXAMPLE_PROJECT_ID` as Actions variable instead of Actions secret.

[example-custom-ci-build-id](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-custom-ci-build-id.yml) was previously running only on v9. I have changed it to run only on v10. Is that acceptable or does the v9 example need to be retained?

This is still in draft state whilst I check through the logs.

**Comment by MikeMcC399** [comment]
- This PR will require further rework after https://github.com/cypress-io/github-action/pull/727 is merged. Leaving in Draft state until the restructure PR is merged.

**Comment by MikeMcC399** [comment]
@jaffrepaul 

I have successfully tested this for the two scenarios:

1. As in https://github.com/cypress-io/github-action with no change to any project id or secrets
2. In a fork with project id and recording key specified via environment variables

so it is now ready for review.

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
@MikeMcC399 I think I would prefer the route of skipping recording on external contributors for this. We employ this strategy on the main cypress repo, since we have the same issue there with external contributors. I don't see it being convenient for external contributors to setup their own example project in this case just to submit a fix. https://github.com/cypress-io/cypress/blob/develop/.circleci/workflows.yml#L484:L484

**Comment by MikeMcC399** [comment]
@jennifer-shehane Thank you for your feedback!

My suggestion was more oriented to users who wanted to use the examples to practice the use of the action rather than just to fix submitters.

I would however not want to force anyone, including fix submitters, to have to set up a Cypress Cloud project.

An easy way out would be to suppress the action from running in a fork, however that would be at the disadvantage of any user who genuinely wanted to get deeper into using the recording examples with low effort, so I don't want to take this route.

A better solution is to add a condition to this proposed PR that recording is only attempted if `secrets.EXAMPLE_RECORDING_KEY` is defined (not `null`). A default fork would not have this secret defined, so this would cover default external contributors.

I will take a look at how to implement this best. In the meantime I have set the PR into Draft status.

**Comment by MikeMcC399** [comment]
- This PR is superseded by https://github.com/cypress-io/github-action/pull/751 which adds the functionality of skipping tests if the Actions secret `secrets.EXAMPLE_RECORDING_KEY` is not defined. Since this was a non-trivial enhancement I elected to put the enhancement into a new PR and leave this one untouched for reference.

**Pull request closed without merging**
