### PR TITLE
feat(deps): update action from node16 to node20

### LINKED ISSUE #968: Release `github-action` for Node.js `node20`
This is an enhancement request for Cypress `github-action`. 

GitHub has now provided support for `node20` in their JavaScript Actions environment. See https://github.com/actions/runner/discussions/2704.

## What would you like?

A new major version of the Cypress `github-action` should be released using GitHub's support for Node.js `20` in GitHub JavaScript Actions.

## Why is this needed?

Cypress needs to be able to run using Node.js `20` and not be restricted to Node.js `16`.

Node.js `16` reaches [end-of-life](https://github.com/nodejs/release#release-schedule) on Sep 11, 2023.

From within `github-action`, the full functionality of Cypress together with Cypress Cloud integration and test summaries is only available when Cypress is called by `github-action` using the [Cypress Module API](https://docs.cypress.io/guides/guides/module-api). This is the default way that the `github-action` calls Cypress since the release of `github-action@v2`. Cypress is called in the context of GitHub's [`runs.using` for JavaScript Actions](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsusing-for-javascript-actions) currently available only as `node16`.

## Other

This enhancement request has a critical dependency on an update to the [`runs.using` for JavaScript Actions](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsusing-for-javascript-actions) environment being provided by GitHub through their [actions/runner](https://github.com/actions/runner).

See https://github.com/actions/runner/discussions/2704 for announcement on the availability of `node20`  support:

> From here, we plan to skip over node 18 and hop on the node 20 LTS release. We are currently working on a date to rollout node 20 and have work in-flight to accomplish this. We will update this discussion in the coming weeks with our plans once we finalize them.

## Workarounds

- The [Custom test command](https://github.com/cypress-io/github-action#custom-test-command) option `command` of `github-action` can be used to call Cypress from the context of the Node.js version set up in the GitHub runner, for instance using [actions/setup-node](https://github.com/actions/setup-node) setting Node.js to `18` or `20`, however this usage bypasses many other functions of `github-action`. It causes many of the other `github-action` options to be ignored and prevents return of detailed results information from the Cypress run, such as the test summary and `resultsUrl`. Using `command` is therefore not a good long-term option.

- An alternative to using the Cypress JavaScript Action `github-action` is to call Cypress from a GitHub workflow directly using [`run`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun), with the same disadvantage as above.

- A further alternative is to call the [Cypress Module API](https://docs.cypress.io/guides/guides/module-api) from a custom script written in JavaScript and called from a custom GitHub Actions workflow. This can be used in a simple way or the full results can be used and processed as needed.

Edit: Above text edited based on information in https://github.com/actions/runner/discussions/2704 Jul 19, 2023.
Updated again on Aug 15, 2023 based on https://github.com/actions/runner/issues/2619#issuecomment-1679003443.
Further update Aug 17, 2023.

### PR DESCRIPTION
**Pull request by MikeMcC399**
BREAKING CHANGE:

- Closes #968

This PR migrates the Cypress JavaScript GitHub Action [cypress-io/github-action](https://github.com/cypress-io/github-action) to run under `node20` instead of under `node16`. This is a BREAKING CHANGE.

## Strategy

`node20` is provided as an option in [GitHub runners](https://github.com/actions/runner) through release [v2.308.0](https://github.com/actions/runner/releases/tag/v2.308.0) from August 14, 2023. The release notes say: 

> *Actions Runner follows a progressive release policy, so the latest release might not be available to your enterprise, organization, or repository yet.*

In practice this means that GitHub-hosted runners pick up the new version within a few days whilst GitHub self-hosted runners may take longer. The GitHub documentation [runs.using](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions) has yet to be updated to list `node20` as an option (status Aug 16, 2023).

Changes made to migrate to `node20` are kept to the minimum to reduce migration risks. Related updates, such as migrating npm `package-lock.json` files from `lockfileVersion` `2` to `3` are deferred.

Initially, the documentation for [cypress-io/github-action](https://github.com/cypress-io/github-action) will continue to recommend using `v5` whilst offering `v6` for "early adopter" users needing `node20` support.

Since Node.js `16` plans to transition into [end-of-life](https://github.com/nodejs/release#release-schedule) on September 11, 2023, this may then be a convenient time to change the recommended action version from `v5` to `v6`, updating the documentation accordingly.

### CODE REVIEW

**Comment by MikeMcC399** [comment]
This PR is feature-complete and passes all tests 🙂 

- I submitted PR https://github.com/cypress-io/github-action/pull/996 to flush out unpublished documentation changes and examples and I suggest that this is merged first before merging this migration PR. I will leave this PR temporarily in draft state for this reason.

**Comment by MikeMcC399** [comment]
I squashed the changes as I wanted to reduce the risk when merging this PR, which is out of my control. It **must** generate a new major version as a BREAKING CHANGE.

**Review by AtofStryker — APPROVED** [review]
Is the version to be published pulled from the changelog? I am not too familiar with the semantic release action. Or do we need to semver a breaking change in the commit @chrisbreiding ?

**Comment by chrisbreiding** [comment]
Looks like the action uses `semantic-release`, so the standard [commit format for a breaking change](https://github.com/semantic-release/semantic-release#commit-message-format) will work.

**Comment by MikeMcC399** [comment]
@AtofStryker

The release process is described in the [CONTRIBUTING](https://github.com/cypress-io/github-action/blob/master/CONTRIBUTING.md) document. There is a separate section on [Merging pull requests](https://github.com/cypress-io/github-action/blob/master/CONTRIBUTING.md#merging-pull-requests).

> Is the version to be published pulled from the changelog?

No. The content of [CHANGELOG.md](https://github.com/MikeMcC399/github-action/blob/migrate/node20/CHANGELOG.md) has no influence on which version is used for the release.

> I am not too familiar with the semantic release action. Or do we need to semver a breaking change in the commit?

The commit https://github.com/cypress-io/github-action/pull/995/commits/affa1e6bef18dda4b414b996833b35a1527d7383 in this PR already includes the `BREAKING CHANGE:` notation:

image

**Comment by AtofStryker** [comment]
@MikeMcC399 squashing and merging usually grabs the PR title, but I believe the commit would still be in the footer so it should work. Do we want to rebase merge to be sure or do you feel it's unnecessary?

**Comment by MikeMcC399** [comment]
@AtofStryker 

> squashing and merging usually grabs the PR title, but I believe the commit would still be in the footer so it should work. Do we want to rebase merge to be sure or do you feel it's unnecessary?

There are different options in a repo as to how squash and merge is set up and they aren't visible to me as Contributor, however when you click on Squash and Merge it shows you what the commit looks like before you execute it. To be doubly sure, just check that it has BREAKING CHANGE: in the body, but I think anyway `@semantic-release/commit-analyzer` will parse the attached commit correctly.

I don't think a rebase merge is necessary, although again as a Contributor I never get to personally do any commits into the `master` branch, so I can only comment theoretically!

Here's what it looked like in my test repo:

```text
[11:30:32 AM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[11:30:32 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: feat(deps): update action from node16 to node20 (#11)

BREAKING CHANGE:

Update action from node16 to node20
update @types/node to 20.5.0
[11:30:32 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is major
[11:30:32 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 3 commits complete: major release
[11:30:32 AM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[11:30:32 AM] [semantic-release] › ℹ  The next release version is 6.0.0

```

**Comment by AtofStryker** [comment]
@MikeMcC399 just merged in with commit messages on. Will try to monitor the job to verify release!

**Comment by MikeMcC399** [comment]
@AtofStryker 

Many thanks! It all went as planned! 🚀 💪🏻

**Pull request merged**
