### PR TITLE
Update example webpack to run under Node.js 18

### PR DESCRIPTION
**Pull request by MikeMcC399**
This PR resolves issue https://github.com/cypress-io/github-action/issues/686 "webpack examples fail locally on Node.js 18 (LTS)"

For

- [examples/v9/webpack](https://github.com/cypress-io/github-action/tree/master/examples/v9/webpack)
- [examples/webpack](https://github.com/cypress-io/github-action/tree/master/examples/webpack)

in `webpack.config.js`

- the deprecated `contentBase` is replaced by [static directory](https://webpack.js.org/configuration/dev-server/#directory)
- [mode](https://webpack.js.org/configuration/mode/) `development` is added and

the versions of the following npm packages are bumped:

- [webpack](https://www.npmjs.com/package/webpack) from 4 to 5.75.0 (latest)
- [webpack-cli](https://www.npmjs.com/package/webpack-cli) from 3 to 5.0.1 (latest)
- [webpack-dev-server](https://www.npmjs.com/package/webpack-dev-server) from 3.11.0 to 4.11.1 (latest)

finally

- a `.gitignore` file is added, which contains `dist/`, to ensure that a local run of the test does not inadvertently cause files created by the test to be committed to the repository.

### GitHub test

Check the Actions log on https://github.com/cypress-io/github-action/actions/workflows/example-webpack.yml?query=branch%3Amaster and ensure that the Status is "Success"

### Local test

Open a terminal window on a local clone of the repository:

```bash
cd examples/v9/webpack
nvm use 18.13.0
npm ci
npx webpack
```
Ensure that the output is:
"webpack 5.75.0 compiled successfully"
and that there are no error messages displayed.

Following on from the previous test to check in `examples/webpack`

```bash
cd ../../webpack
nvm use 18.13.0
npm ci
npx webpack
```

Ensure that the output is:
"webpack 5.75.0 compiled successfully"
and that there are no error messages displayed.

Execute
```bash
git status
```

and check that no new files are found by `git`.

### CODE REVIEW

**Comment by MikeMcC399** [comment]
- This PR will require rework after https://github.com/cypress-io/github-action/pull/727 is merged. Leaving in Draft state until the restructure PR is merged.

**Comment by MikeMcC399** [comment]
example-webpack successful run is logged in [3966929200](https://github.com/cypress-io/github-action/actions/runs/3966929200)

**Comment by MikeMcC399** [comment]
- In draft pending https://github.com/cypress-io/github-action/pull/747

**Comment by MikeMcC399** [comment]
@jaffrepaul 

This PR is now rebased and ready for review and merge.

**Review by jaffrepaul — APPROVED** [review]
👍

**Pull request merged**
