### PR TITLE
fix: resolve PNPM 7 support issues

### PR DESCRIPTION
**Pull request by naorpeled**

### CODE REVIEW

**Comment by MikeMcC399** [comment]
@naorpeled 

Will you describe what issue this PR resolves? 

[.github/workflows/example-basic-pnpm.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-basic-pnpm.yml) successfully runs using pnpm 7.26.0 (see [4009465323](https://github.com/cypress-io/github-action/actions/runs/4009465323)).

If you want to change the action, you also need to 

1. Execute `npm run format`
2. Execute `npm run build`
3. commit the results with git

(See https://github.com/cypress-io/github-action/issues/742.)

**Comment by naorpeled** [comment]
> @naorpeled
> 
> Will you describe what issue this PR resolves?
> 
> [.github/workflows/example-basic-pnpm.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-basic-pnpm.yml?rgh-link-date=2023-01-30T11%3A43%3A12Z) successfully runs using pnpm 7.26.0 (see [4009465323](https://github.com/cypress-io/github-action/actions/runs/4009465323)).
> 
> If you want to change the action, you also need to
> 
> 1. Execute `npm run format`
> 2. Execute `npm run build`
> 3. commit the results with git
> 
> (See #742.)

Hey,
when running the Cypress verify command the workflow fails with the following error:

```Command failed: /home/runner/work/.../node_modules/.bin/cypress verify```

My guess was that we would need to run the new `pnpm exec` command to make this work properly because PNPM made some breaking changes in v7.
This PR isn't ready at all btw, was just playing around to see if it would work.

**Comment by MikeMcC399** [comment]
Hi @naorpeled 

Thank you for the background information!

Did you try running `npx cypress verify`?

That worked for me with the example [.github/workflows/example-basic-pnpm.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-basic-pnpm.yml).

**Comment by naorpeled** [comment]
> Hi @naorpeled
> 
> Thank you for the background information!
> 
> Did you try running `npx cypress verify`?
> 
> That worked for me with the example [.github/workflows/example-basic-pnpm.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-basic-pnpm.yml?rgh-link-date=2023-01-30T13%3A15%3A22Z).

we didn't disable the binaries download so that happens in the workflow anyways from what I understand.

**Comment by MikeMcC399** [comment]
@naorpeled 

It might be worth submitting a issue in parallel to the PR to describe the problem with pnpm v7 with this action, including a reproducible example to test against.

**Comment by MikeMcC399** [comment]
- Since the associated issue #761 was closed due to inactivity, it would make sense to close this PR as well. There hasn't been any new activity in either the issue or this PR from @naorpeled since January 2023.

**Pull request closed without merging**
