### PR TITLE
feat: add yarn berry / modern (version 2 and later) examples

### PR DESCRIPTION
**Pull request by MikeMcC399**
This PR is related to issue #799 "Examples for Yarn 1 (Classic) and Yarn Berry / Modern (Version 2 and later)" and it complements the Yarn 1 (Classic) examples added through PR #828.

It provides new examples for Yarn Modern under the directories:

- `examples/yarn-modern`
- `examples/v9/yarn-modern`

together with a new corresponding workflow

- `example-yarn-modern.yml`
an update to the following script to automate maintenance updates to `cypress@latest`

- `scripts/update-cypress-latest-other.sh`

and an update to

- `README.md`

### Local

```bash
nvm use 18 # for node v18.15.0
npm install yarn -g
yarn -v
```

expect `1.22.19`

#### Yarn Modern with Cypress 9.7.0

From root of repository ...

```bash
cd examples/v9/yarn-modern
yarn -v # should yield 3.4.1
yarn
yarn test
```

Confirm Cypress test passes.

#### Yarn Modern with Cypress 12.8.1

From root of repository ...

```bash
cd examples/yarn-modern
yarn -v # should yield 3.4.1
yarn
yarn test
```

Confirm Cypress test passes.

### Update script

From root of repository ...

```bash
cd examples/yarn-modern
yarn add cypress@12.0.0 -D # install older version
cd ../..
npm run update:cypress
cd examples/yarn-modern
yarn info cypress --name-only
```

Confirm that Cypress has been updated to latest version (12.8.1).

### GitHub

Manually run the workflow

- `example-yarn-modern.yml`

and confirm success.

### CODE REVIEW

**Review by AtofStryker — APPROVED** [review]

**Review by lmiller1990 — APPROVED** [review]
Thanks!!

**Comment by MikeMcC399** [comment]
@lmiller1990 

Many thanks for merging! Now that Yarn Classic and Modern are documented, I will follow up by documenting `pnpm`, which was not documented at all when support for this package manager was added to the action.

**Comment by MikeMcC399** [comment]
@lmiller1990 

If you are able to, please follow the instructions in [Updating the latest version in GitHub Marketplace](https://github.com/cypress-io/github-action/blob/master/DEVELOPMENT.md#updating-the-latest-version-in-github-marketplace) since the [Marketplace version](https://github.com/marketplace/actions/cypress-io) is lagging behind at v5.3.1.

If not, then perhaps @jaffrepaul will need to take action?

**Comment by lmiller1990** [comment]
Thanks @MikeMcC399, done! The marketplace now shows 5.5.1 as the latest.

**Pull request merged**
