### PR TITLE
Resolve sporadic failures in example-start running multiple servers

### PR DESCRIPTION
**Pull request by MikeMcC399**
This PR resolves issue https://github.com/cypress-io/github-action/issues/657 "CI: Sporadic failures in example-start running multiple servers".

It modifies the action [.github/workflows/example-start.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-start.yml):

1. by disabling [update-check](https://www.npmjs.com/package/update-check) through environment variable `NO_UPDATE_CHECK` = 1 and
2. by updating [serve](https://www.npmjs.com/package/serve) to the latest version (14.1.2). [serve Version 14](https://github.com/vercel/serve#usage) requires a minimum of Node.js 14. This is compatible with [GHA v5](https://github.com/cypress-io/github-action/releases/tag/v5.0.0) which removes Node.js 12 support. (The Node.js 14 version is in [maintenance status](https://github.com/nodejs/release#release-schedule) and is currently available as version [Node.js 14.21.1](https://nodejs.org/download/release/latest-v14.x/).)

## Verification

Check that jobs of https://github.com/cypress-io/github-action/actions/workflows/example-start.yml are now regularly succeeding.

## Release

The commits are tagged with `test:` which does not cause a release to be triggered. The PR only affects the CI runs of `github-action`, not the executable part of `github-action`.

The commits should be automatically listed in the release notes when a later PR with `fix:`, `feat:` or `perf:` commit tag is merged.

### CODE REVIEW

**Comment by MikeMcC399** [comment]
@jaffrepaul 

All tests were successful!

**Comment by jaffrepaul** [comment]
Thanks @MikeMcC399! The action version bumps are handled in [this PR](https://github.com/cypress-io/github-action/pull/644). Let me try to get that merged today so you can rebase master and this will be even smaller.

**Comment by MikeMcC399** [comment]
Waiting for #644

**Comment by MikeMcC399** [comment]
@jaffrepaul 

Thank you for the merge of your #644! Rebasing this PR was painless and as luck would have it all tests have passed!

So it's over to you now.

**Review by jaffrepaul — APPROVED** [review]

**Pull request merged**
