### PR TITLE
fix(deps): combined renovate bot bumps

### PR DESCRIPTION
**Pull request by jaffrepaul**
Combined GH dependency & dev deps bumps, dist rebuild

### CODE REVIEW

**Comment by MikeMcC399** [comment]
Hi @jaffrepaul 

It's good you managed to bump some dependencies!

This PR (https://github.com/cypress-io/github-action/pull/716) did not result in any release when it was merged, even though it contained the following commit message, which is not what I expected. I though there would be a release.

`fix(deps): combined renovate bot bumps`

See https://github.com/cypress-io/github-action/actions/runs/3876387669/jobs/6610173204

```text
[5:57:11 PM] [semantic-release] › ℹ  Found git tag v5.0.4 associated with version 5.0.4 on branch master
[5:57:11 PM] [semantic-release] › ℹ  Found 8 commits since last release
[5:57:11 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[5:57:11 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Merge pull request #716 from cypress-io/fix/group-renovate-dependency-updates

fix(deps): combined renovate bot bumps
[5:57:11 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[5:57:11 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: combined GH dep & dev dep bump, dist rebuild
[5:57:11 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
```
---

What is your expectation? Does something need to be done here?

**Comment by jaffrepaul** [comment]
@MikeMcC399 I was expecting the same, that's actually why I merged this. I'll get a look at the keys again.

**Comment by MikeMcC399** [comment]
@jaffrepaul 

I think it is probably the release configuration, not the keys. If I find anything I will let you know.

**Comment by jaffrepaul** [comment]
@MikeMcC399 that's what I'm thinking as well. Any time you can put towards it would be a massive help, as always!

**Comment by MikeMcC399** [comment]
@jaffrepaul 

My guess was wrong. It is not the configuration which causes the issue.

The explanation why there was no release triggered is that `fix(deps):` was in the wrong place. In https://github.com/cypress-io/github-action/actions/runs/3876387669/jobs/6610173204 there are two commits related to this PR (https://github.com/cypress-io/github-action/pull/716):

```text
2a6db85 Merge pull request #716 from cypress-io/fix/group-renovate-dependency-updates
be440e1 combined GH dep & dev dep bump, dist rebuild
```

Neither of these commits has `fix(deps):` in the subject, so they were passed over by semantic-release.

The solution to this for future PRs / commits:

1. When creating a change, put the semantic-release information into the commit. This is what I have been doing.
2. When merging a PR make sure that there is a semantic-release trigger in:
   - one of the commits in the PR or
   - in the subject of the merge commit

Maybe some more specific guidance should be put into the [DEVELOPMENT.md](https://github.com/cypress-io/github-action/blob/master/DEVELOPMENT.md)?
 
---

Troubleshooting tools:

`git log --oneline` shows `<hash> <title-line>` of commits. `<title-line>` is where semantic-release is searching. 
`git log --pretty=format:"%h %s"` is an alternative which eliminates the branch information

**Pull request merged**
