### PR TITLE
fix: rebuild dist files

### PR DESCRIPTION
**Pull request by piotrekkr**

### CODE REVIEW

**Comment by piotrekkr** [comment]
@mjhenkes Can you have a look? I just cloned master and run `npm run build`

**Comment by piotrekkr** [comment]
@mellis481 I tried running action  as `piotrekkr/github-action@update-dist-files` and I did not get any warnings from GitHub any more.

**Comment by lwhiteley** [comment]
@mellis481 looking deeper at the code the set-output just seems to be a name of the command being issued.
The actual action being done is not the old one as the library has been updated

**Comment by jaffrepaul** [comment]
> [piotrekkr](/piotrekkr)

Thank you everyone for your contributions here and in the other thread(s). 

I'm going to get a closer look at this immediately following the holiday. I'd rather not kick off a new build right before most people will be afk.

In the interim @piotrekkr please sign the CLA agreement above so that I'll be able to merge this PR.

Also, this repo needs some attention to address some failing tests (unrelated to this work) and outdated deps. This is likely to be included in an initiative moving forward to keep Cypress tools better maintained. Contributions are always welcome.

**Comment by piotrekkr** [comment]
@jaffrepaul I signed  CLA and also updated and force pushed commit message. Is it okay now?

**Review by jaffrepaul — APPROVED** [review]
Confirmed the deprecation message is now gone in a test build. 

Merging this to trigger a new release 🎉

**Pull request merged**
