### PR TITLE
Update Docker examples in README to Node.js 18

### PR DESCRIPTION
**Pull request by MikeMcC399**
This PR resolves the documentation issue https://github.com/cypress-io/github-action/issues/680 "Example uses Docker image with end-of-life Node.js 12".

In the documentation examples

- [Docker image](https://github.com/cypress-io/github-action#docker-image) 
- [Firefox](https://github.com/cypress-io/github-action#firefox)

the Cypress Docker image

- [cypress/browsers:node18.12.0-chrome106-ff106](https://github.com/cypress-io/cypress-docker-images/tree/master/browsers/node18.12.0-chrome106-ff106) is substituted for the 

- [cypress/browsers:node12.13.0-chrome78-ff70](https://github.com/cypress-io/cypress-docker-images/tree/master/browsers/node12.13.0-chrome78-ff70) Docker image,

since Node.js 12 already passed End-of-Life last year on 2022-04-30 according to the [End-of-Life Releases](https://github.com/nodejs/release#end-of-life-releases) list.

## Verification

Create a new workflow `example-docker.yml` in the `.github/workflows` directory of a local copy of a fork of this repository as below:

```yml
name: E2E in custom container
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    # Cypress Docker image with Chrome v106
    # and Firefox v106 pre-installed
    container: cypress/browsers:node18.12.0-chrome106-ff106
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v5
        with:
          browser: chrome
          working-directory: examples/basic
```

Push the example to the repository and ensure that the action log shows that it ran successfully.

Similarly for the Firefox example.

### CODE REVIEW

**Comment by MikeMcC399** [comment]
@jaffrepaul / @jennifer-shehane 

Perhaps one of you could also review this PR from last month?

**Comment by jaffrepaul** [comment]
@MikeMcC399 this is high on my list of the older PRs to get a look at. I should have time by the end of the week 🥂

**Comment by MikeMcC399** [comment]
@jaffrepaul 

> this is high on my list of the older PRs to get a look at. I should have time by the end of the week

Thank you. It's non-critical. I just wanted to make sure it hadn't got forgotten. I understand though that there's a lot going on at the moment.

**Comment by jaffrepaul** [comment]
I'm seeing this initialize correctly
Screen Shot 2023-01-27 at 5 51 38 PM

But the run output uses node 16
Screen Shot 2023-01-27 at 5 51 58 PM

**Comment by MikeMcC399** [comment]
@jaffrepaul 
> But the run output uses node 16 

This conforms to the GitHub documentation  [`runs` for JavaScript actions](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions) and 

https://github.com/cypress-io/github-action/blob/821aeac6ccc722db3d43469e398f88e83a5fd05e/action.yml#L90-L92

which selects the action to run under `node16`.

- See also the discussion in issue https://github.com/cypress-io/github-action/issues/642.

**Comment by jaffrepaul** [comment]
Cool, just making sure that was all aligning as expected.

**Review by jaffrepaul — APPROVED** [review]

**Pull request merged**
