### PR TITLE
feat: add parameter spec to run limited list of tests

### PR DESCRIPTION
**Pull request by gmmcal**
As per discussed on #49, I'm adding support for spec parameter on test run.

Prof of working feature: https://github.com/gmmcal/cypress-gh-action-example/commit/bfc8a8d10d2c13239dd1c7b680cc63c913ea566a/checks?check_suite_id=370536915

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@bahmutov Does this repo need CLA set up?

**Comment by gmmcal** [comment]
Just noticed that this is the first external contribution in this repo :)

**Comment by bahmutov** [comment]
oh yes, we do need CLA for this repo, will set it up

**Comment by gmmcal** [comment]
Hey @bahmutov CLA is signed. I can do two things about item 2:

1. add example for this case in README, as requested.
2. create a follow up PR changing README and mapping all options shown in the code with proper explanation. For example, I had a HUGE hard time trying to understand and make this action to work properly because I was running a yarn command that would start the server and run the tests instead of just starting the server. 

What fit's you better?

**Comment by bahmutov** [comment]
I would start with just issue 1 - just add an example for this pull request, and open an issue for issue 2, which we can tackle separately

**Comment by gmmcal** [comment]
deal!

**Comment by gmmcal** [comment]
@bahmutov ready for appreciation :)

**Pull request merged**
