### PR TITLE
chore(deps): update cypress to 13.3.2

### PR DESCRIPTION
**Pull request by Julien-Marcou**
This PR updates the [examples](https://github.com/cypress-io/github-action/tree/master/examples) to [Cypress 13.3.2](https://docs.cypress.io/guides/references/changelog#13-3-2) released Oct 18, 2023.

### CODE REVIEW

**Comment by MikeMcC399** [comment]
@Julien-Marcou 
- Could you please clarify if the Cypress team asked you to submit this PR or if it was your own idea? I ask this because I have submitted PRs for each of the previous 20 releases since Cypress `12.8.0` in March of this year.
- Are you intending to carry out this maintenance task for future releases of Cypress or is this a one-off submission? 
- Since you have not previously contributed to this repository the workflows that could check whether the PR is successful are blocked and need to be approved.

**Comment by Julien-Marcou** [comment]
> @Julien-Marcou
> 
> * Could you please clarify if the Cypress team asked you to submit this PR or if it was your own idea? I ask this because I have submitted PRs for each of the previous 20 releases since Cypress `12.8.0` in March of this year.
> * Are you intending to carry out this maintenance task for future releases of Cypress or is this a one-off submission?
> * Since you have not previously contributed to this repository the workflows that could check whether the PR is successful are blocked and need to be approved.

@MikeMcC399 

- It was my idea
- No I don't intend to carry out this maintenance
- Yes, I was expecting the PR to be blocked until someone approved it

This PR is in line with several PRs I'm doing across some GitHub/Cypress repositories, as Node 20.8.1, which is a security release, has been released a few days ago, I wanted to sync all the dependencies of one of my project to align everything with at least Node 20.8.1 and Cypress 13.3.2

I wanted to then update the docker image example in an upcoming PR, something like that:

```diff
     # from https://hub.docker.com/r/cypress/browsers/tags
     container:
-      image: cypress/browsers:node-20.5.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
+      image: cypress/browsers:node-20.8.1-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
```

I know the changes are only for examples (so there is no real security issue here), but I thought I could take the opportunity to change them at the same time 🙂

**Review by jennifer-shehane — APPROVED** [review]

**Comment by jennifer-shehane** [comment]
Thanks @Julien-Marcou

**Comment by Julien-Marcou** [comment]
Rebased 👍

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

You've approved this PR, however it hasn't been merged. What are your plans for this?

**Comment by MikeMcC399** [comment]
@Julien-Marcou 

Yesterday, Oct 23, 2023, [Cypress 13.3.3](https://docs.cypress.io/guides/references/changelog#13-3-3) was released, so this PR is now obsoleted and should be closed.

- I've submitted https://github.com/cypress-io/github-action/pull/1067 to update the examples to the new version.

**Pull request closed without merging**
